// This file was generated by SquareLine Vision Exporter
// Project name: DESK MEDIA DEVICEV2 UI

#include "../GUI.h"

// COMPONENT background_img

lv_obj_t *ui_background_img_create(lv_obj_t *comp_parent) {
  lv_obj_t *cui_background_img_root_t6w9H2coiOYuik;
  cui_background_img_root_t6w9H2coiOYuik = lv_obj_create(comp_parent);
  lv_obj_remove_style_all(cui_background_img_root_t6w9H2coiOYuik);
  lv_obj_set_width(cui_background_img_root_t6w9H2coiOYuik, LV_SIZE_CONTENT);
  lv_obj_set_height(cui_background_img_root_t6w9H2coiOYuik, LV_SIZE_CONTENT);
  lv_obj_set_align(cui_background_img_root_t6w9H2coiOYuik, LV_ALIGN_CENTER);
  lv_obj_remove_flag(cui_background_img_root_t6w9H2coiOYuik,
                     LV_OBJ_FLAG_CLICKABLE);
  lv_obj_remove_flag(cui_background_img_root_t6w9H2coiOYuik,
                     LV_OBJ_FLAG_SCROLLABLE);

  lv_obj_t *cui_Base_image_JPQjuEoHuTVYTN;
  cui_Base_image_JPQjuEoHuTVYTN =
      lv_image_create(cui_background_img_root_t6w9H2coiOYuik);
  lv_obj_set_width(cui_Base_image_JPQjuEoHuTVYTN, LV_SIZE_CONTENT);
  lv_obj_set_height(cui_Base_image_JPQjuEoHuTVYTN, LV_SIZE_CONTENT);
  lv_obj_set_align(cui_Base_image_JPQjuEoHuTVYTN, LV_ALIGN_CENTER);
  lv_image_set_src(cui_Base_image_JPQjuEoHuTVYTN,
                   &upload_bg2_8b751f9997764edca3d7f03db3dd4a54_png);
  lv_obj_add_flag(cui_Base_image_JPQjuEoHuTVYTN, LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_remove_flag(cui_Base_image_JPQjuEoHuTVYTN, LV_OBJ_FLAG_SCROLLABLE);

  lv_obj_t **children =
      lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BACKGROUND_IMG_NUM);
  children[UI_COMP_BACKGROUND_IMG] = cui_background_img_root_t6w9H2coiOYuik;
  children[UI_COMP_BACKGROUND_IMG_BASE] = cui_Base_image_JPQjuEoHuTVYTN;
  lv_obj_add_event_cb(cui_background_img_root_t6w9H2coiOYuik,
                      get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD,
                      children);
  lv_obj_add_event_cb(cui_background_img_root_t6w9H2coiOYuik,
                      del_component_child_event_cb, LV_EVENT_DELETE, children);
  ui_comp_background_img_create_hook(cui_background_img_root_t6w9H2coiOYuik);
  return cui_background_img_root_t6w9H2coiOYuik;
}
