// This file was generated by SquareLine Vision Exporter
// Project name: DESK MEDIA DEVICEV2 UI

#include "../GUI.h"

void ui_comp_background_img_create_hook(lv_obj_t *comp) {
}

void ui_comp_textarea_create_hook(lv_obj_t *comp) {
}
