// This file was generated by SquareLine Vision Exporter
// Project name: DESK MEDIA DEVICEV2 UI

#ifndef _UI_COMP_TEXTAREA_H
#define _UI_COMP_TEXTAREA_H

#include "../GUI.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT textarea
#define UI_COMP_TEXTAREA 0
#define UI_COMP_TEXTAREA_BASE 1
#define _UI_COMP_TEXTAREA_NUM 2
lv_obj_t *ui_textarea_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
