// This file was generated by SquareLine Vision Exporter
// Project name: DESK MEDIA DEVICEV2 UI

#include "../GUI.h"

// COMPONENT textarea

lv_obj_t *ui_textarea_create(lv_obj_t *comp_parent) {
  lv_obj_t *cui_textarea_root_QR0AHJNtEX9BC3;
  cui_textarea_root_QR0AHJNtEX9BC3 = lv_obj_create(comp_parent);
  lv_obj_remove_style_all(cui_textarea_root_QR0AHJNtEX9BC3);
  lv_obj_set_width(cui_textarea_root_QR0AHJNtEX9BC3, 395);
  lv_obj_set_height(cui_textarea_root_QR0AHJNtEX9BC3, 330);
  lv_obj_set_align(cui_textarea_root_QR0AHJNtEX9BC3, LV_ALIGN_CENTER);
  lv_obj_remove_flag(cui_textarea_root_QR0AHJNtEX9BC3, LV_OBJ_FLAG_CLICKABLE);
  lv_obj_remove_flag(cui_textarea_root_QR0AHJNtEX9BC3, LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_layout(cui_textarea_root_QR0AHJNtEX9BC3, LV_LAYOUT_FLEX);
  lv_obj_set_flex_flow(cui_textarea_root_QR0AHJNtEX9BC3, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(cui_textarea_root_QR0AHJNtEX9BC3, LV_FLEX_ALIGN_CENTER,
                        LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_set_style_pad_row(cui_textarea_root_QR0AHJNtEX9BC3, 10,
                           LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(cui_textarea_root_QR0AHJNtEX9BC3, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_t *cui_Base_textarea_5KrYqWAAW30Vc2;
  cui_Base_textarea_5KrYqWAAW30Vc2 =
      lv_textarea_create(cui_textarea_root_QR0AHJNtEX9BC3);
  lv_obj_set_width(cui_Base_textarea_5KrYqWAAW30Vc2, 395);
  lv_obj_set_height(cui_Base_textarea_5KrYqWAAW30Vc2, 330);
  lv_obj_set_align(cui_Base_textarea_5KrYqWAAW30Vc2, LV_ALIGN_CENTER);
  lv_obj_set_layout(cui_Base_textarea_5KrYqWAAW30Vc2, LV_LAYOUT_FLEX);
  lv_obj_set_flex_flow(cui_Base_textarea_5KrYqWAAW30Vc2, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(cui_Base_textarea_5KrYqWAAW30Vc2, LV_FLEX_ALIGN_START,
                        LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
  lv_obj_set_style_pad_row(cui_Base_textarea_5KrYqWAAW30Vc2, 0,
                           LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(cui_Base_textarea_5KrYqWAAW30Vc2, 0,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(cui_Base_textarea_5KrYqWAAW30Vc2, 5,
                          LV_PART_MAIN | LV_STATE_DEFAULT);
  ui_object_set_themeable_style_property(
      cui_Base_textarea_5KrYqWAAW30Vc2, LV_PART_MAIN | LV_STATE_DEFAULT,
      LV_STYLE_BG_COLOR, _ui_theme_bg_color_white);
  ui_object_set_themeable_style_property(
      cui_Base_textarea_5KrYqWAAW30Vc2, LV_PART_MAIN | LV_STATE_DEFAULT,
      LV_STYLE_BG_OPA, _ui_theme_bg_opa_white);
  ui_object_set_themeable_style_property(
      cui_Base_textarea_5KrYqWAAW30Vc2, LV_PART_MAIN | LV_STATE_DEFAULT,
      LV_STYLE_BG_GRAD_COLOR, _ui_theme_grad_color_white);
  ui_object_set_themeable_style_property(
      cui_Base_textarea_5KrYqWAAW30Vc2, LV_PART_MAIN | LV_STATE_DEFAULT,
      LV_STYLE_BG_GRAD_DIR, _ui_theme_grad_dir_white);
  lv_obj_set_layout(cui_Base_textarea_5KrYqWAAW30Vc2, LV_LAYOUT_FLEX);
  lv_obj_set_flex_flow(cui_Base_textarea_5KrYqWAAW30Vc2, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(cui_Base_textarea_5KrYqWAAW30Vc2, LV_FLEX_ALIGN_START,
                        LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
  lv_obj_set_style_pad_row(cui_Base_textarea_5KrYqWAAW30Vc2, 0,
                           LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(cui_Base_textarea_5KrYqWAAW30Vc2, 0,
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_color(cui_Base_textarea_5KrYqWAAW30Vc2,
                                 lv_color_hex(0x000000),
                                 LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_opa(cui_Base_textarea_5KrYqWAAW30Vc2, 255,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_width(cui_Base_textarea_5KrYqWAAW30Vc2, 2,
                                 LV_PART_SELECTED | LV_STATE_DEFAULT);
  lv_obj_set_style_outline_pad(cui_Base_textarea_5KrYqWAAW30Vc2, 0,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

  lv_obj_t **children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TEXTAREA_NUM);
  children[UI_COMP_TEXTAREA] = cui_textarea_root_QR0AHJNtEX9BC3;
  children[UI_COMP_TEXTAREA_BASE] = cui_Base_textarea_5KrYqWAAW30Vc2;
  lv_obj_add_event_cb(cui_textarea_root_QR0AHJNtEX9BC3,
                      get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD,
                      children);
  lv_obj_add_event_cb(cui_textarea_root_QR0AHJNtEX9BC3,
                      del_component_child_event_cb, LV_EVENT_DELETE, children);
  ui_comp_textarea_create_hook(cui_textarea_root_QR0AHJNtEX9BC3);
  return cui_textarea_root_QR0AHJNtEX9BC3;
}
