// This file was generated by SquareLine Vision Exporter
// Project name: DESK MEDIA DEVICEV2 UI

#ifndef _UI_COMP_BACKGROUND_IMG_H
#define _UI_COMP_BACKGROUND_IMG_H

#include "../GUI.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT background_img
#define UI_COMP_BACKGROUND_IMG 0
#define UI_COMP_BACKGROUND_IMG_BASE 1
#define _UI_COMP_BACKGROUND_IMG_NUM 2
lv_obj_t *ui_background_img_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
