// This file was generated by SquareLine Vision Exporter
// Project name: DESK MEDIA DEVICEV2 UI

#ifndef _DESK_MEDIA_DEVICEV2_UI_UI_COMP_HOOK_H
#define _DESK_MEDIA_DEVICEV2_UI_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_background_img_create_hook(lv_obj_t *comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
